version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_DB=${TS_DB_NAME:-mydb}
      - POSTGRES_USER=${TS_DB_USER:-myuser}
      - POSTGRES_PASSWORD=${TS_DB_PASSWORD:-mypassword}
      # 你可以根据需要添加更多 TimescaleDB/Postgres 环境变量
    ports:
      - "${TS_DB_PORT:-5432}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
