version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_DB=${TS_DB_NAME:-mydb}
      - POSTGRES_USER=${TS_DB_USER:-myuser}
      - POSTGRES_PASSWORD=${TS_DB_PASSWORD:-mypassword}
      # 你可以根据需要添加更多 TimescaleDB/Postgres 环境变量
    ports:
      - "${TS_DB_PORT:-5432}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_PORT}:8123"
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
volumes:
  clickhouse_data:
  clickhouse_logs: 
  timescale_data:
  redis_data:
